# Default - landing page
server {
    listen 80;
    server_name localhost;

    location / {
        return 200 "MAESTRO — <a href='https://odysseus.velociraptor-tint.ts.net/'>Odysseus</a> | <a href='https://grafana.velociraptor-tint.ts.net/'>Grafana</a>";
    }
}

# Odysseus
server {
    listen 80;
    server_name odysseus.velociraptor-tint.ts.net;

    location / {
        proxy_pass http://odysseus-odysseus-1:7000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 86400;
    }
}